--
-- DYNAMIC_BASKET
--
-- I move the key cols in the front, maybe not needed
CREATE TABLE DYNAMIC_BASKET_HISTORY
   (
      EVENT_ID         DECIMAL(38),
      BASKET_ID        VARCHAR(8),
      INSTANCE         INTEGER,
      IMPACTED_AMOUNT  DECIMAL(15,6),
      EXPIRATION_DATE  TIMESTAMP,
      REMAINING_AMOUNT DECIMAL,
      OFFER_CODE       VARCHAR(20),
      CALL_START       TIMESTAMP,
      SNAPSHOT_DATE    DATE NOT NULL
   )
WITH (appendonly=true, COMPRESSTYPE=QUICKLZ)
DISTRIBUTED BY (EVENT_ID)  -- we need a distribution key so our join is local
PARTITION BY RANGE (SNAPSHOT_DATE)
(
  START (date '2015-01-01') INCLUSIVE
  END (date '2016-12-31') INCLUSIVE
  EVERY (INTERVAL '1 DAY')
)
;

--
-- DYNAMIC_BASKET_EXT - daily load 
--
CREATE EXTERNAL TABLE DYNAMIC_BASKET_EXT
   (
      IMPACTED_AMOUNT  DECIMAL(15,6),
      EXPIRATION_DATE  TIMESTAMP,
      REMAINING_AMOUNT DECIMAL,
      BASKET_ID        VARCHAR(8),
      INSTANCE         INTEGER,
      EVENT_ID         DECIMAL(38),
      OFFER_CODE       VARCHAR(20),
      CALL_START       TIMESTAMP
   )
LOCATION ('pxf://pivhdsne:50070/xd/job-jdbc/dynamic_basket_daily.csv?profile=HdfsTextSimple')
FORMAT 'text' (delimiter E',' null '')
SEGMENT REJECT LIMIT 1000 ROWS
;


--
-- POPULATE NEW DATE
--

INSERT INTO DYNAMIC_BASKET

SELECT 
IMPACTED_AMOUNT,
EXPIRATION_DATE,
REMAINING_AMOUNT,
BASKET_ID,
INSTANCE,
EVENT_ID,
OFFER_CODE,
CALL_START,
CURRENT_DATE

FROM DYNAMIC_BASKET_EXT;



--
-- UPDATE VIEW TO SEE ONLY LATEST INSERT
--

CREATE OR REPLACE VIEW DYNAMIC_BASKET_CURRENT
SELECT 
IMPACTED_AMOUNT,
EXPIRATION_DATE,
REMAINING_AMOUNT,
BASKET_ID,
INSTANCE,
EVENT_ID,
OFFER_CODE,
CALL_START
FROM 
DYNAMIC_BASKET_HIST
WHERE SNAPSHOT_DATE = 'SELECT CURRENT_DATE'  -- check and see if it create the view with a hard coded date. if not we need to put this on a function
;



